# SmokePhysAI Configuration

# Data configuration
data:
  grid_size: [128, 128]
  sequence_length: 20
  num_train: 800
  num_val: 200
  cache_dir: "./cache"

# Model configuration
model:
  input_dim: 128
  hidden_dim: 512
  num_layers: 6
  num_heads: 8
  output_channels: 64
  chaos_strength: 0.1

# Physics constraint configuration
physics:
  conservation_weight: 1.0
  continuity_weight: 1.0
  energy_weight: 0.5

# Training configuration
training:
  batch_size: 8
  num_epochs: 100
  learning_rate: 0.001
  weight_decay: 0.01

# Simulation configuration
simulation:
  dt: 0.01
  viscosity: 0.001
  grid_size: [128, 128]